/**
 * Industry page data — ALL stats verified from peer-reviewed or credible sources.
 * Source index at bottom of file.
 */
export const INDUSTRY_DATA = {
  hotels: {
    headline: 'The sound of five-star hospitality',
    subheadline: 'From lobby to spa, we design the music that shapes your guest experience across every zone.',
    heroImage: '/images/hero-hotel.webp',
    stats: [
      { value: '9.1%', label: 'Revenue Increase' },
      { value: '41%', label: 'Longer Dwell Time' },
      { value: '39%', label: 'More Return Visits' },
      { value: '24/7', label: 'Music Management' },
    ],
    zonesTitle: 'Every space has its frequency',
    zones: [
      { name: 'Lobby & Reception', description: 'Warm, welcoming, refined — the first impression that sets the tone' },
      { name: 'Restaurant & F&B', description: 'From intimate dinner to vibrant breakfast buffet' },
      { name: 'Spa & Wellness', description: 'Tranquil, meditative soundscapes for deep relaxation' },
      { name: 'Pool & Outdoor', description: 'Relaxed, upbeat energy for sun and leisure' },
      { name: 'Gym & Fitness', description: 'Energetic, motivating tracks that push performance' },
      { name: 'Bar & Lounge', description: 'Sophisticated evening ambiance, jazz to deep house' },
    ],
    benefitsTitle: 'Why hotels choose BMAsia',
    benefits: [
      'Centralized multi-property control from one dashboard',
      'Bespoke music design by our team, refreshed quarterly',
      'Daypart scheduling — automatic transitions from morning to night',
      'Offline playback guaranteed — music plays even if internet drops',
      '24/7 dedicated support and account management',
    ],
    editorialStat: '41% of guests stay longer when they enjoy the music.',
    editorialStatSub: 'MRC Data / Soundtrack Your Brand, 2021 — 2,500+ consumers surveyed.',
    editorialImage: '/images/hero-hotel.webp',
    ctaHeadline: "Design your hotel's sound.",
  },
  restaurants: {
    headline: 'The secret ingredient no one sees',
    subheadline: 'Music that turns meals into memories — scheduled, curated, and always on brand.',
    heroImage: '/images/hero-restaurant.webp',
    stats: [
      { value: '9.1%', label: 'Higher Revenue' },
      { value: '15%', label: 'More Dessert Sales' },
      { value: '24%', label: 'Longer Dining Time' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'From sunrise to last call',
    zones: [
      { name: 'Fine Dining', description: 'Elegant, intimate, classical — enhancing the culinary experience' },
      { name: 'Casual Dining', description: 'Warm, conversational, easy — music that doesn\'t compete' },
      { name: 'Café & Bakery', description: 'Light, cheerful, acoustic — the perfect backdrop' },
      { name: 'Bar & Cocktails', description: 'Sophisticated, jazzy, social — setting the evening mood' },
      { name: 'Fast Casual & QSR', description: 'Upbeat, energetic, modern — matching the pace' },
      { name: 'Outdoor Terrace', description: 'Breezy, relaxed, sunset — al fresco vibes' },
    ],
    benefitsTitle: 'Why restaurants choose BMAsia',
    benefits: [
      'Daypart scheduling — automatic transitions from breakfast to late night',
      'Genre and mood curation matched to your F&B concept',
      'All licenses available — royalty-free or commercial options',
      'Multi-zone control for dining room, bar, terrace, and restrooms',
      'Volume and energy auto-adjust based on time of day',
    ],
    editorialStat: 'Slow-tempo music increases dining time by 24% and bar revenue by 40%.',
    editorialStatSub: 'Milliman (1986), Journal of Consumer Research.',
    editorialImage: '/images/hero-restaurant.webp',
    ctaHeadline: 'Set the mood for your restaurant.',
  },
  retail: {
    headline: 'Your brand has a sound',
    subheadline: 'We design the sonic identity that makes customers stay, browse, and buy.',
    heroImage: '/images/hero-retail.webp',
    stats: [
      { value: '38%', label: 'Higher Daily Sales' },
      { value: '90%', label: 'Return with Good Music' },
      { value: '3.4x', label: 'Wine Priming Effect' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'Sound for every format',
    zones: [
      { name: 'Fashion & Apparel', description: 'Trendy, curated playlists that match your brand identity' },
      { name: 'Shopping Malls', description: 'Dynamic, energetic music that drives foot traffic' },
      { name: 'Beauty & Wellness', description: 'Calming, luxurious soundscapes for pampering' },
      { name: 'Showrooms', description: 'Premium, aspirational music that elevates products' },
      { name: 'Supermarkets', description: 'Upbeat, familiar music that keeps shoppers moving' },
      { name: 'Gyms & Fitness', description: 'High-energy BPM tracks for peak performance' },
    ],
    benefitsTitle: 'Why retailers choose BMAsia',
    benefits: [
      'Centralized music control across all store locations',
      'Brand-aligned curation that reinforces your identity',
      'Audio messaging for promotions, store hours, and announcements',
      'Multi-store consistency from flagship to outlet',
      'Peak hour scheduling — energy levels match customer flow',
    ],
    editorialStat: 'Slow-tempo music increases daily retail sales by 38%.',
    editorialStatSub: 'Milliman (1982), Journal of Marketing — the gold-standard retail music study.',
    editorialImage: '/images/hero-retail.webp',
    ctaHeadline: 'Amplify your brand.',
  },
  bars: {
    headline: 'Where the night sounds right',
    subheadline: 'Licensed music that sets the perfect mood — from cocktail hour to closing time.',
    heroImage: '/images/hero-restaurant.webp',
    stats: [
      { value: '+31%', label: 'More Drinks Ordered' },
      { value: '+40%', label: 'Bar Revenue Increase' },
      { value: '24%', label: 'Longer Table Time' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'Set the vibe for every moment',
    zones: [
      { name: 'Cocktail Bar', description: 'Sophisticated jazz, neo-soul, and bossa nova' },
      { name: 'Sports Bar', description: 'High-energy hits and crowd-pleasers' },
      { name: 'Wine Bar', description: 'Intimate, acoustic, refined — letting conversation flow' },
      { name: 'Rooftop Lounge', description: 'Chill electronic, sunset vibes, deep house' },
      { name: 'Nightclub', description: 'Dance floor energy, DJ-curated sets' },
      { name: 'Hotel Bar', description: 'Elegant, brand-consistent evening ambiance' },
    ],
    benefitsTitle: 'Why bars choose BMAsia',
    benefits: [
      'Mood transitions from after-work to late night automatically',
      'Genre expertise — from jazz to electronic to top 40',
      'Legal compliance — no risk of copyright issues',
      'Volume scheduling that respects noise regulations',
      'Bespoke playlists refreshed to keep regulars surprised',
    ],
    editorialStat: 'Higher volume increased drinks per patron from 2.6 to 3.4.',
    editorialStatSub: 'Guéguen et al. (2004), Alcoholism: Clinical & Experimental Research.',
    editorialImage: '/images/hero-restaurant.webp',
    ctaHeadline: "Design your bar's sound.",
  },
  spas: {
    headline: 'Sound as therapy',
    subheadline: 'Music designed to calm, heal, and restore — from reception to treatment room.',
    heroImage: '/images/hero-medical.webp',
    stats: [
      { value: '65%', label: 'Anxiety Reduction' },
      { value: '60 BPM', label: 'Alpha Brainwave Sync' },
      { value: '30K+', label: 'Curated Tracks' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'Healing frequencies for every space',
    zones: [
      { name: 'Reception & Waiting', description: 'Gentle transition from outside world to sanctuary' },
      { name: 'Treatment Rooms', description: 'Deep relaxation, nature sounds, ambient textures' },
      { name: 'Yoga & Meditation', description: 'Mindful, spacious soundscapes for practice' },
      { name: 'Pool & Thermal', description: 'Flowing water-inspired ambient compositions' },
      { name: 'Relaxation Lounge', description: 'Post-treatment serenity, soft and warm' },
      { name: 'Changing Areas', description: 'Light, unobtrusive background comfort' },
    ],
    benefitsTitle: 'Why spas choose BMAsia',
    benefits: [
      'Curated wellness playlists by professional music designers',
      'Seamless zone-by-zone control for different treatment areas',
      'Offline playback — never silence during a treatment',
      'Seasonal and thematic updates (Ramadan, holidays, events)',
      'All licenses included with Beat Breeze — zero hassle',
    ],
    editorialStat: '"Weightless" reduced anxiety by 65% in clinical testing.',
    editorialStatSub: 'Mindlab International / British Academy of Sound Therapy, 2011.',
    editorialImage: '/images/hero-medical.webp',
    ctaHeadline: "Design your sanctuary's sound.",
  },
  cafes: {
    headline: 'The perfect backdrop',
    subheadline: 'Music that makes people sit down, order another coffee, and stay a while.',
    heroImage: '/images/hero-cafe.webp',
    stats: [
      { value: '79%', label: 'Notice the Music' },
      { value: '41%', label: 'Stay Longer' },
      { value: '73%', label: 'Take Action After' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'From morning espresso to afternoon work session',
    zones: [
      { name: 'Morning Rush', description: 'Upbeat acoustic, gentle energy to start the day' },
      { name: 'Work & Study Hours', description: 'Lo-fi, ambient, focus-friendly — no distractions' },
      { name: 'Afternoon Social', description: 'Warm indie, folk, light pop — conversational' },
      { name: 'Evening Wind-Down', description: 'Jazz, bossa nova, mellow — a natural transition' },
      { name: 'Weekend Brunch', description: 'Cheerful, curated, slightly louder — brunch energy' },
      { name: 'Outdoor Seating', description: 'Light and airy — complementing street sounds' },
    ],
    benefitsTitle: 'Why cafés choose BMAsia',
    benefits: [
      'Daypart scheduling matches energy to the time of day',
      'All licenses included — no collection society fees with Beat Breeze',
      'Affordable pricing for single-zone locations',
      'Easy setup on any Android or Windows device',
      'Refreshed playlists keep regulars engaged',
    ],
    editorialStat: '73% of customers take action after hearing a song they like in a café.',
    editorialStatSub: 'MRC Data / Soundtrack Your Brand, 2021.',
    editorialImage: '/images/hero-cafe.webp',
    ctaHeadline: "Design your café's sound.",
  },
  malls: {
    headline: 'Sound that moves shoppers',
    subheadline: 'Multi-zone music management for shopping centers that want more foot traffic and longer visits.',
    heroImage: '/images/hero-retail.webp',
    stats: [
      { value: '38%', label: 'Higher Daily Sales' },
      { value: '85%', label: 'Say Music Lifts Mood' },
      { value: '75%', label: 'Stay Longer' },
      { value: '24/7', label: 'Centralized Control' },
    ],
    zonesTitle: 'One building, many moods',
    zones: [
      { name: 'Common Areas', description: 'Upbeat, diverse, welcoming — setting the mall energy' },
      { name: 'Food Court', description: 'Lively, social, complementing the dining buzz' },
      { name: 'Parking & Entrances', description: 'Subtle welcome cues and wayfinding' },
      { name: 'Premium Zones', description: 'Refined, luxury-adjacent music for high-end wings' },
      { name: 'Kids & Entertainment', description: 'Fun, playful, family-friendly' },
      { name: 'Restrooms & Service Areas', description: 'Light, clean, unobtrusive' },
    ],
    benefitsTitle: 'Why shopping malls choose BMAsia',
    benefits: [
      'Centralized management across dozens of zones from one dashboard',
      'Audio messaging for promotions, events, and announcements',
      'Scheduling that adapts to weekday vs weekend traffic patterns',
      'Hardware solutions for large-scale deployments',
      'Dedicated account manager for ongoing support',
    ],
    editorialStat: '85% of shoppers say music is the #1 factor lifting their in-store mood.',
    editorialStatSub: 'Mood Media, "Quantifying the Impact of Sensory Marketing," 2019.',
    editorialImage: '/images/hero-retail.webp',
    ctaHeadline: "Design your mall's sound.",
  },
  gyms: {
    headline: 'Energy on demand',
    subheadline: 'High-energy music that pushes performance, motivates members, and keeps them coming back.',
    heroImage: '/images/hero-gym.webp',
    stats: [
      { value: '+15%', label: 'Endurance Increase' },
      { value: '-10%', label: 'Perceived Exertion' },
      { value: '139', label: 'Studies Confirm It' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'Different energy for every workout',
    zones: [
      { name: 'Weights Floor', description: 'Heavy beats, hip-hop, high BPM — raw energy' },
      { name: 'Cardio Zone', description: 'Driving electronic, pop remixes, steady pace' },
      { name: 'Group Classes', description: 'Instructor-curated, synced to workout phases' },
      { name: 'Yoga & Stretch', description: 'Ambient, calming, breath-focused' },
      { name: 'Reception & Lounge', description: 'Upbeat but welcoming — transition space' },
      { name: 'Changing Rooms', description: 'Light, neutral, personal space' },
    ],
    benefitsTitle: 'Why gyms choose BMAsia',
    benefits: [
      'BPM-matched playlists for different workout intensities',
      'Multi-zone control — heavy in weights, calm in yoga',
      'All licenses available — commercial or royalty-free',
      'Scheduling that adapts to peak hours and class schedules',
      'Multi-location consistency for gym chains',
    ],
    editorialStat: 'Music increases endurance by 15% and reduces perceived exertion by 10%.',
    editorialStatSub: 'Karageorghis et al. / Terry et al. (2020), Psychological Bulletin — meta-analysis of 139 studies.',
    editorialImage: '/images/hero-gym.webp',
    ctaHeadline: "Power up your gym's sound.",
  },
  medical: {
    headline: 'Calm, trust, comfort',
    subheadline: 'Music that reduces anxiety, builds trust, and creates a healing environment.',
    heroImage: '/images/hero-medical.webp',
    stats: [
      { value: 'NNT=4', label: 'As Effective as Medication' },
      { value: '7,385', label: 'Patients Studied' },
      { value: '92', label: 'Clinical Trials' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'Sound for every clinical space',
    zones: [
      { name: 'Waiting Room', description: 'Calming, reassuring — reducing pre-appointment anxiety' },
      { name: 'Treatment Rooms', description: 'Gentle background that supports focus and comfort' },
      { name: 'Recovery Areas', description: 'Soft, healing ambient compositions' },
      { name: 'Dental Chairs', description: 'Masking clinical sounds with soothing music' },
      { name: 'Aesthetic Clinics', description: 'Premium, spa-like atmosphere for beauty treatments' },
      { name: 'Staff Areas', description: 'Light, positive energy for break rooms' },
    ],
    benefitsTitle: 'Why medical facilities choose BMAsia',
    benefits: [
      'Clinically-informed playlists designed for healthcare settings',
      'All licenses included with Beat Breeze — no compliance complexity',
      'Offline playback — no interruptions during treatments',
      'Volume control appropriate for clinical environments',
      'Easy setup that doesn\'t burden IT teams',
    ],
    editorialStat: 'Music reduces surgical anxiety as effectively as medication (NNT=4).',
    editorialStatSub: 'Kuhlmann et al. (2018), British Journal of Surgery — 92 RCTs, 7,385 patients.',
    editorialImage: '/images/hero-medical.webp',
    ctaHeadline: "Design your practice's sound.",
  },
  offices: {
    headline: 'Productive by design',
    subheadline: 'Background music that boosts focus, creativity, and workplace satisfaction.',
    heroImage: '/images/hero-hotel.webp',
    stats: [
      { value: '79%', label: 'Say Music Helps' },
      { value: '70 dB', label: 'Optimal Level' },
      { value: '30K+', label: 'Curated Tracks' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'Different modes for different spaces',
    zones: [
      { name: 'Open Plan', description: 'Ambient, focus-friendly — masking distracting conversations' },
      { name: 'Reception & Lobby', description: 'Professional, welcoming — first impressions matter' },
      { name: 'Meeting Rooms', description: 'Subtle pre-meeting energy, silence during sessions' },
      { name: 'Break Rooms & Cafeteria', description: 'Upbeat, social — recharging energy' },
      { name: 'Co-Working Spaces', description: 'Lo-fi, productive — the modern work soundtrack' },
      { name: 'Executive Floors', description: 'Refined, understated, premium ambiance' },
    ],
    benefitsTitle: 'Why offices choose BMAsia',
    benefits: [
      'Scheduling that matches office rhythms — focus mornings, social afternoons',
      'Multi-zone control for open plan, meeting rooms, and common areas',
      'All licenses included with Beat Breeze — IT-friendly setup',
      'Employee satisfaction boost through thoughtful sound design',
      'Affordable single-zone pricing for smaller offices',
    ],
    editorialStat: 'Software developers produce higher quality work with background music.',
    editorialStatSub: 'Lesiuk (2005), Psychology of Music — 56 developers, 5-week study.',
    editorialImage: '/images/hero-hotel.webp',
    ctaHeadline: "Design your workspace's sound.",
  },
  showrooms: {
    headline: 'Sound that sells the dream',
    subheadline: 'Premium music that elevates products and creates aspirational experiences.',
    heroImage: '/images/hero-retail.webp',
    stats: [
      { value: '38%', label: 'Higher Sales' },
      { value: '3.4x', label: 'Music Priming Effect' },
      { value: '65%', label: 'Say Atmosphere Matters' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'Setting the stage for every product',
    zones: [
      { name: 'Automotive Showrooms', description: 'Premium, aspirational — matching the brand' },
      { name: 'Property Sales Centers', description: 'Sophisticated lifestyle soundtrack' },
      { name: 'Luxury Brand Showrooms', description: 'Editorial, fashion-forward, curated' },
      { name: 'Tech & Electronics', description: 'Modern, innovative, forward-thinking' },
      { name: 'Furniture & Design', description: 'Warm, homelike, inspiring' },
      { name: 'Art Galleries', description: 'Minimal, contemplative, enhancing not competing' },
    ],
    benefitsTitle: 'Why showrooms choose BMAsia',
    benefits: [
      'Brand-aligned music that reinforces your product positioning',
      'Event mode for launches, openings, and VIP viewings',
      'Bespoke curation that tells your brand story through sound',
      'Multi-room scheduling for different product areas',
      'Premium feel without the premium complexity',
    ],
    editorialStat: 'Classical music leads customers to choose more expensive products.',
    editorialStatSub: 'Areni & Kim (1993), Advances in Consumer Research.',
    editorialImage: '/images/hero-retail.webp',
    ctaHeadline: "Design your showroom's sound.",
  },
  events: {
    headline: 'Every event has a sound',
    subheadline: 'From corporate galas to brand launches — music that makes moments unforgettable.',
    heroImage: '/images/hero-hotel.webp',
    stats: [
      { value: '63%', label: 'Brand Connection' },
      { value: '90%', label: 'Welcome Brand Presence' },
      { value: '500+', label: 'Venues Served' },
      { value: '23+', label: 'Years Experience' },
    ],
    zonesTitle: 'Sound for every occasion',
    zones: [
      { name: 'Corporate Events', description: 'Professional, polished, brand-appropriate' },
      { name: 'Product Launches', description: 'Exciting, modern, building anticipation' },
      { name: 'Weddings & Celebrations', description: 'Emotional, personal, perfectly timed' },
      { name: 'Conferences', description: 'Energizing breaks, focused sessions' },
      { name: 'Exhibitions', description: 'Dynamic, engaging, guiding the visitor journey' },
      { name: 'Private Functions', description: 'Curated to the host\'s taste and the event\'s mood' },
    ],
    benefitsTitle: 'Why event venues choose BMAsia',
    benefits: [
      'Event-specific playlist design by our music team',
      'Scheduling that follows event timelines precisely',
      'Audio messaging for announcements and program flow',
      'Temporary or permanent installation options',
      'Our Music Design Assistant helps plan events in minutes',
    ],
    editorialStat: 'At peak emotional moments, attendees are 63% more likely to connect with brands.',
    editorialStatSub: 'Live Nation, "The Power of Live" Global Study, 2018 — 22,500 fans, 11 countries.',
    editorialImage: '/images/hero-hotel.webp',
    ctaHeadline: "Design your event's sound.",
  },
};

/**
 * SOURCE INDEX — all stats traceable to these studies:
 *
 * 1. Milliman (1982) — Journal of Marketing, 46(3). Supermarket: slow music = +38% daily sales.
 * 2. Milliman (1986) — Journal of Consumer Research, 13(2). Restaurant: slow music = 24% longer, +40% bar revenue.
 * 3. HUI Research / SYB (2017) — 1.8M transactions, 16 restaurants. Brand-fit = +9.1%, +15% desserts.
 * 4. MRC Data / SYB (2021) — 2,500+ US consumers. 41% dwell, 39% return, 79% notice, 73% take action.
 * 5. North, Hargreaves & McKendrick (1999) — Nature / J. Applied Psychology. French/German wine priming.
 * 6. Kuhlmann et al. (2018) — British Journal of Surgery. 92 RCTs, 7,385 patients. NNT=4 for anxiety.
 * 7. Terry & Karageorghis et al. (2020) — Psychological Bulletin. 139 studies. +15% endurance, -10% RPE.
 * 8. Guéguen et al. (2004) — Alcoholism: Clinical & Experimental Research. Volume → +31% drinks.
 * 9. Mindlab International (2011) — "Weightless" = 65% anxiety reduction.
 * 10. Mood Media (2019) — 10,000+ consumers, 8 countries. 85% mood, 90% return, 78% atmosphere.
 * 11. Lesiuk (2005) — Psychology of Music. Music improves developer quality-of-work.
 * 12. Live Nation (2018) — "Power of Live." 22,500 fans. 63% brand connection, 90% welcome brands.
 * 13. Areni & Kim (1993) — Advances in Consumer Research. Classical music → premium purchases.
 * 14. Thoma et al. (2013) — PLOS ONE. Music → faster cortisol recovery.
 */
