export const INDUSTRY_DATA = {
  hotels: {
    headline: 'The sound of five-star hospitality',
    subheadline: 'From lobby to spa, we design the music that shapes your guest experience across every zone.',
    heroImage: '/images/hero-hotel.webp',
    stats: [
      { value: '500+', label: 'Hotel Locations' },
      { value: '93%', label: 'Guest Differentiation' },
      { value: '9.1%', label: 'Revenue Impact' },
      { value: '24/7', label: 'Music Management' },
    ],
    zonesTitle: 'Every space has its frequency',
    zones: [
      { name: 'Lobby & Reception', description: 'Warm, welcoming, refined — the first impression that sets the tone' },
      { name: 'Restaurant & F&B', description: 'From intimate dinner to vibrant breakfast buffet' },
      { name: 'Spa & Wellness', description: 'Tranquil, meditative soundscapes for deep relaxation' },
      { name: 'Pool & Outdoor', description: 'Relaxed, upbeat energy for sun and leisure' },
      { name: 'Gym & Fitness', description: 'Energetic, motivating tracks that push performance' },
      { name: 'Bar & Lounge', description: 'Sophisticated evening ambiance, jazz to deep house' },
    ],
    benefitsTitle: 'Why hotels choose BMAsia',
    benefits: [
      'Centralized multi-property control from one dashboard',
      'Bespoke music design by our team, refreshed quarterly',
      'Daypart scheduling — automatic transitions from morning to night',
      'Offline playback guaranteed — music plays even if internet drops',
      '24/7 dedicated support and account management',
    ],
    editorialStat: '93% of guests say music differentiates their experience.',
    editorialStatSub: 'Sound is the invisible luxury your guests remember.',
    editorialImage: '/images/hero-hotel.webp',
    ctaHeadline: "Design your hotel's sound.",
  },
  restaurants: {
    headline: 'The secret ingredient no one sees',
    subheadline: 'Music that turns meals into memories — scheduled, curated, and always on brand.',
    heroImage: '/images/hero-restaurant.webp',
    stats: [
      { value: '9.1%', label: 'Higher Average Check' },
      { value: '15.6%', label: 'More Dessert Sales' },
      { value: '42%', label: 'Longer Dwell Time' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'From sunrise to last call',
    zones: [
      { name: 'Fine Dining', description: 'Elegant, intimate, classical — enhancing the culinary experience' },
      { name: 'Casual Dining', description: 'Warm, conversational, easy — music that doesn\'t compete' },
      { name: 'Café & Bakery', description: 'Light, cheerful, acoustic — the perfect backdrop' },
      { name: 'Bar & Cocktails', description: 'Sophisticated, jazzy, social — setting the evening mood' },
      { name: 'Fast Casual & QSR', description: 'Upbeat, energetic, modern — matching the pace' },
      { name: 'Outdoor Terrace', description: 'Breezy, relaxed, sunset — al fresco vibes' },
    ],
    benefitsTitle: 'Why restaurants choose BMAsia',
    benefits: [
      'Daypart scheduling — automatic transitions from breakfast to late night',
      'Genre and mood curation matched to your F&B concept',
      'All licenses available — royalty-free or commercial options',
      'Multi-zone control for dining room, bar, terrace, and restrooms',
      'Volume and energy auto-adjust based on time of day',
    ],
    editorialStat: '9.1% higher revenue with curated music.',
    editorialStatSub: '1.8 million purchases. 16 locations. The data speaks.',
    editorialImage: '/images/hero-restaurant.webp',
    ctaHeadline: 'Set the mood for your restaurant.',
  },
  retail: {
    headline: 'Your brand has a sound',
    subheadline: 'We design the sonic identity that makes customers stay, browse, and buy.',
    heroImage: '/images/hero-retail.webp',
    stats: [
      { value: '37%', label: 'Sales Increase' },
      { value: '42%', label: 'Longer Browsing' },
      { value: '85%', label: 'Brand Recall' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'Sound for every format',
    zones: [
      { name: 'Fashion & Apparel', description: 'Trendy, curated playlists that match your brand identity' },
      { name: 'Shopping Malls', description: 'Dynamic, energetic music that drives foot traffic' },
      { name: 'Beauty & Wellness', description: 'Calming, luxurious soundscapes for pampering' },
      { name: 'Showrooms', description: 'Premium, aspirational music that elevates products' },
      { name: 'Supermarkets', description: 'Upbeat, familiar music that keeps shoppers moving' },
      { name: 'Gyms & Fitness', description: 'High-energy BPM tracks for peak performance' },
    ],
    benefitsTitle: 'Why retailers choose BMAsia',
    benefits: [
      'Centralized music control across all store locations',
      'Brand-aligned curation that reinforces your identity',
      'Audio messaging for promotions, store hours, and announcements',
      'Multi-store consistency from flagship to outlet',
      'Peak hour scheduling — energy levels match customer flow',
    ],
    editorialStat: '37% sales increase with brand-fit music.',
    editorialStatSub: 'Sound is the new visual merchandising.',
    editorialImage: '/images/hero-retail.webp',
    ctaHeadline: 'Amplify your brand.',
  },
  bars: {
    headline: 'Where the night sounds right',
    subheadline: 'Licensed music that sets the perfect mood — from cocktail hour to closing time.',
    heroImage: '/images/hero-restaurant.webp',
    stats: [
      { value: '54.9%', label: 'Stay Longer Due to Music' },
      { value: '41%', label: 'Spend More with Better Music' },
      { value: '100M+', label: 'Tracks Available' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'Set the vibe for every moment',
    zones: [
      { name: 'Cocktail Bar', description: 'Sophisticated jazz, neo-soul, and bossa nova' },
      { name: 'Sports Bar', description: 'High-energy hits and crowd-pleasers' },
      { name: 'Wine Bar', description: 'Intimate, acoustic, refined — letting conversation flow' },
      { name: 'Rooftop Lounge', description: 'Chill electronic, sunset vibes, deep house' },
      { name: 'Nightclub', description: 'Dance floor energy, DJ-curated sets' },
      { name: 'Hotel Bar', description: 'Elegant, brand-consistent evening ambiance' },
    ],
    benefitsTitle: 'Why bars choose BMAsia',
    benefits: [
      'Mood transitions from after-work to late night automatically',
      'Genre expertise — from jazz to electronic to top 40',
      'Legal compliance — no risk of copyright issues',
      'Volume scheduling that respects noise regulations',
      'Bespoke playlists refreshed to keep regulars surprised',
    ],
    editorialStat: '54.9% of people stay longer because of the music.',
    editorialStatSub: 'The right playlist keeps the tab open.',
    editorialImage: '/images/hero-restaurant.webp',
    ctaHeadline: 'Design your bar\'s sound.',
  },
  spas: {
    headline: 'Sound as therapy',
    subheadline: 'Music designed to calm, heal, and restore — from reception to treatment room.',
    heroImage: '/images/hero-medical.webp',
    stats: [
      { value: '40%', label: 'Anxiety Reduction' },
      { value: '93%', label: 'Guests Value Music' },
      { value: '30K+', label: 'Curated Tracks' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'Healing frequencies for every space',
    zones: [
      { name: 'Reception & Waiting', description: 'Gentle transition from outside world to sanctuary' },
      { name: 'Treatment Rooms', description: 'Deep relaxation, nature sounds, ambient textures' },
      { name: 'Yoga & Meditation', description: 'Mindful, spacious soundscapes for practice' },
      { name: 'Pool & Thermal', description: 'Flowing water-inspired ambient compositions' },
      { name: 'Relaxation Lounge', description: 'Post-treatment serenity, soft and warm' },
      { name: 'Changing Areas', description: 'Light, unobtrusive background comfort' },
    ],
    benefitsTitle: 'Why spas choose BMAsia',
    benefits: [
      'Curated wellness playlists by professional music designers',
      'Seamless zone-by-zone control for different treatment areas',
      'Offline playback — never silence during a treatment',
      'Seasonal and thematic updates (Ramadan, holidays, events)',
      'All licenses included with Beat Breeze — zero hassle',
    ],
    editorialStat: 'Music reduces patient anxiety by up to 40%.',
    editorialStatSub: 'Sound is the most underused wellness tool.',
    editorialImage: '/images/hero-medical.webp',
    ctaHeadline: 'Design your sanctuary\'s sound.',
  },
  cafes: {
    headline: 'The perfect backdrop',
    subheadline: 'Music that makes people sit down, order another coffee, and stay a while.',
    heroImage: '/images/hero-cafe.webp',
    stats: [
      { value: '42%', label: 'Longer Dwell Time' },
      { value: '84.5%', label: 'Notice Background Music' },
      { value: '30K+', label: 'Curated Tracks' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'From morning espresso to afternoon work session',
    zones: [
      { name: 'Morning Rush', description: 'Upbeat acoustic, gentle energy to start the day' },
      { name: 'Work & Study Hours', description: 'Lo-fi, ambient, focus-friendly — no distractions' },
      { name: 'Afternoon Social', description: 'Warm indie, folk, light pop — conversational' },
      { name: 'Evening Wind-Down', description: 'Jazz, bossa nova, mellow — a natural transition' },
      { name: 'Weekend Brunch', description: 'Cheerful, curated, slightly louder — brunch energy' },
      { name: 'Outdoor Seating', description: 'Light and airy — complementing street sounds' },
    ],
    benefitsTitle: 'Why cafés choose BMAsia',
    benefits: [
      'Daypart scheduling matches energy to the time of day',
      'All licenses included — no VCPMC/MPC/COMPASS fees with Beat Breeze',
      'Affordable pricing for single-zone locations',
      'Easy setup on any Android or Windows device',
      'Refreshed playlists keep regulars engaged',
    ],
    editorialStat: '84.5% of customers notice the background music.',
    editorialStatSub: 'It\'s never just background. It\'s the experience.',
    editorialImage: '/images/hero-cafe.webp',
    ctaHeadline: 'Design your café\'s sound.',
  },
  malls: {
    headline: 'Sound that moves shoppers',
    subheadline: 'Multi-zone music management for shopping centers that want more foot traffic and longer visits.',
    heroImage: '/images/hero-retail.webp',
    stats: [
      { value: '37%', label: 'Sales Lift' },
      { value: '42%', label: 'Longer Visits' },
      { value: '100M+', label: 'Tracks Available' },
      { value: '24/7', label: 'Centralized Control' },
    ],
    zonesTitle: 'One building, many moods',
    zones: [
      { name: 'Common Areas', description: 'Upbeat, diverse, welcoming — setting the mall energy' },
      { name: 'Food Court', description: 'Lively, social, complementing the dining buzz' },
      { name: 'Parking & Entrances', description: 'Subtle welcome cues and wayfinding' },
      { name: 'Premium Zones', description: 'Refined, luxury-adjacent music for high-end wings' },
      { name: 'Kids & Entertainment', description: 'Fun, playful, family-friendly' },
      { name: 'Restrooms & Service Areas', description: 'Light, clean, unobtrusive' },
    ],
    benefitsTitle: 'Why shopping malls choose BMAsia',
    benefits: [
      'Centralized management across dozens of zones from one dashboard',
      'Audio messaging for promotions, events, and announcements',
      'Scheduling that adapts to weekday vs weekend traffic patterns',
      'Hardware solutions for large-scale deployments',
      'Dedicated account manager for ongoing support',
    ],
    editorialStat: '42% longer visits with curated music.',
    editorialStatSub: 'Every extra minute is revenue.',
    editorialImage: '/images/hero-retail.webp',
    ctaHeadline: 'Design your mall\'s sound.',
  },
  gyms: {
    headline: 'Energy on demand',
    subheadline: 'High-energy music that pushes performance, motivates members, and keeps them coming back.',
    heroImage: '/images/hero-gym.webp',
    stats: [
      { value: '40.8%', label: 'Stay Longer with Good Music' },
      { value: '81.4%', label: 'Notice Background Music' },
      { value: '100M+', label: 'Tracks Available' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'Different energy for every workout',
    zones: [
      { name: 'Weights Floor', description: 'Heavy beats, hip-hop, high BPM — raw energy' },
      { name: 'Cardio Zone', description: 'Driving electronic, pop remixes, steady pace' },
      { name: 'Group Classes', description: 'Instructor-curated, synced to workout phases' },
      { name: 'Yoga & Stretch', description: 'Ambient, calming, breath-focused' },
      { name: 'Reception & Lounge', description: 'Upbeat but welcoming — transition space' },
      { name: 'Changing Rooms', description: 'Light, neutral, personal space' },
    ],
    benefitsTitle: 'Why gyms choose BMAsia',
    benefits: [
      'BPM-matched playlists for different workout intensities',
      'Multi-zone control — heavy in weights, calm in yoga',
      'All licenses available — commercial or royalty-free',
      'Scheduling that adapts to peak hours and class schedules',
      'Multi-location consistency for gym chains',
    ],
    editorialStat: '40.8% of members stay longer when they like the music.',
    editorialStatSub: 'Retention starts with the right playlist.',
    editorialImage: '/images/hero-gym.webp',
    ctaHeadline: 'Power up your gym\'s sound.',
  },
  medical: {
    headline: 'Calm, trust, comfort',
    subheadline: 'Music that reduces anxiety, builds trust, and creates a healing environment.',
    heroImage: '/images/hero-medical.webp',
    stats: [
      { value: '40%', label: 'Anxiety Reduction' },
      { value: '93%', label: 'Patients Value Music' },
      { value: '30K+', label: 'Curated Tracks' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'Sound for every clinical space',
    zones: [
      { name: 'Waiting Room', description: 'Calming, reassuring — reducing pre-appointment anxiety' },
      { name: 'Treatment Rooms', description: 'Gentle background that supports focus and comfort' },
      { name: 'Recovery Areas', description: 'Soft, healing ambient compositions' },
      { name: 'Dental Chairs', description: 'Masking clinical sounds with soothing music' },
      { name: 'Aesthetic Clinics', description: 'Premium, spa-like atmosphere for beauty treatments' },
      { name: 'Staff Areas', description: 'Light, positive energy for break rooms' },
    ],
    benefitsTitle: 'Why medical facilities choose BMAsia',
    benefits: [
      'Clinically-informed playlists designed for healthcare settings',
      'All licenses included with Beat Breeze — no compliance complexity',
      'Offline playback — no interruptions during treatments',
      'Volume control appropriate for clinical environments',
      'Easy setup that doesn\'t burden IT teams',
    ],
    editorialStat: 'Music reduces patient anxiety by up to 40%.',
    editorialStatSub: 'The prescription your waiting room needs.',
    editorialImage: '/images/hero-medical.webp',
    ctaHeadline: 'Design your practice\'s sound.',
  },
  offices: {
    headline: 'Productive by design',
    subheadline: 'Background music that boosts focus, creativity, and workplace satisfaction.',
    heroImage: '/images/hero-hotel.webp',
    stats: [
      { value: '65%', label: 'Report Better Focus' },
      { value: '58.7%', label: 'Value Workplace Music' },
      { value: '30K+', label: 'Curated Tracks' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'Different modes for different spaces',
    zones: [
      { name: 'Open Plan', description: 'Ambient, focus-friendly — masking distracting conversations' },
      { name: 'Reception & Lobby', description: 'Professional, welcoming — first impressions matter' },
      { name: 'Meeting Rooms', description: 'Subtle pre-meeting energy, silence during sessions' },
      { name: 'Break Rooms & Cafeteria', description: 'Upbeat, social — recharging energy' },
      { name: 'Co-Working Spaces', description: 'Lo-fi, productive — the modern work soundtrack' },
      { name: 'Executive Floors', description: 'Refined, understated, premium ambiance' },
    ],
    benefitsTitle: 'Why offices choose BMAsia',
    benefits: [
      'Scheduling that matches office rhythms — focus mornings, social afternoons',
      'Multi-zone control for open plan, meeting rooms, and common areas',
      'All licenses included with Beat Breeze — IT-friendly setup',
      'Employee satisfaction boost through thoughtful sound design',
      'Affordable single-zone pricing for smaller offices',
    ],
    editorialStat: '58.7% of employees value background music at work.',
    editorialStatSub: 'Sound shapes how your team thinks and creates.',
    editorialImage: '/images/hero-hotel.webp',
    ctaHeadline: 'Design your workspace\'s sound.',
  },
  showrooms: {
    headline: 'Sound that sells the dream',
    subheadline: 'Premium music that elevates products and creates aspirational experiences.',
    heroImage: '/images/hero-retail.webp',
    stats: [
      { value: '37%', label: 'Sales Increase' },
      { value: '85%', label: 'Brand Recall' },
      { value: '100M+', label: 'Tracks Available' },
      { value: '24/7', label: 'Automated' },
    ],
    zonesTitle: 'Setting the stage for every product',
    zones: [
      { name: 'Automotive Showrooms', description: 'Premium, aspirational — matching the brand' },
      { name: 'Property Sales Centers', description: 'Sophisticated lifestyle soundtrack' },
      { name: 'Luxury Brand Showrooms', description: 'Editorial, fashion-forward, curated' },
      { name: 'Tech & Electronics', description: 'Modern, innovative, forward-thinking' },
      { name: 'Furniture & Design', description: 'Warm, homelike, inspiring' },
      { name: 'Art Galleries', description: 'Minimal, contemplative, enhancing not competing' },
    ],
    benefitsTitle: 'Why showrooms choose BMAsia',
    benefits: [
      'Brand-aligned music that reinforces your product positioning',
      'Event mode for launches, openings, and VIP viewings',
      'Bespoke curation that tells your brand story through sound',
      'Multi-room scheduling for different product areas',
      'Premium feel without the premium complexity',
    ],
    editorialStat: '85% higher brand recall with intentional music.',
    editorialStatSub: 'Your product deserves a soundtrack.',
    editorialImage: '/images/hero-retail.webp',
    ctaHeadline: 'Design your showroom\'s sound.',
  },
  events: {
    headline: 'Every event has a sound',
    subheadline: 'From corporate galas to brand launches — music that makes moments unforgettable.',
    heroImage: '/images/hero-hotel.webp',
    stats: [
      { value: '93%', label: 'Say Music Matters' },
      { value: '500+', label: 'Venues Served' },
      { value: '100M+', label: 'Tracks Available' },
      { value: '23+', label: 'Years Experience' },
    ],
    zonesTitle: 'Sound for every occasion',
    zones: [
      { name: 'Corporate Events', description: 'Professional, polished, brand-appropriate' },
      { name: 'Product Launches', description: 'Exciting, modern, building anticipation' },
      { name: 'Weddings & Celebrations', description: 'Emotional, personal, perfectly timed' },
      { name: 'Conferences', description: 'Energizing breaks, focused sessions' },
      { name: 'Exhibitions', description: 'Dynamic, engaging, guiding the visitor journey' },
      { name: 'Private Functions', description: 'Curated to the host\'s taste and the event\'s mood' },
    ],
    benefitsTitle: 'Why event venues choose BMAsia',
    benefits: [
      'Event-specific playlist design by our music team',
      'Scheduling that follows event timelines precisely',
      'Audio messaging for announcements and program flow',
      'Temporary or permanent installation options',
      'Our Music Design Assistant helps plan events in minutes',
    ],
    editorialStat: '93% of attendees say music shapes their event experience.',
    editorialStatSub: 'The difference between an event and an experience.',
    editorialImage: '/images/hero-hotel.webp',
    ctaHeadline: 'Design your event\'s sound.',
  },
} as const;
