import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — BMAsia',
  description: 'Terms and conditions for using the BMAsia website.',
};

export default function TermsPage() {
  return (
    <main className="bg-[#0f0f0f] pt-28 pb-20 px-6 md:px-12">
      <article className="max-w-3xl mx-auto prose-invert">
        <p className="font-label text-brand-orange text-xs tracking-[0.3em] uppercase mb-4">Legal</p>
        <h1 className="font-headline text-4xl md:text-5xl text-white mb-4">Terms of Service</h1>
        <p className="text-white/40 text-sm mb-12">Last updated: 9 April 2026</p>

        <div className="space-y-10 text-white/70 leading-relaxed">
          <section>
            <h2 className="font-headline text-2xl text-white mb-4">1. About These Terms</h2>
            <p>These terms govern your use of the BMAsia website at bmasiamusic.com (&ldquo;the Site&rdquo;). By using the Site, you agree to these terms. If you do not agree, please do not use the Site.</p>
            <p className="mt-3">The Site is operated by BMAsia (Thailand) Co., Ltd. and BMAsia Limited (collectively, &ldquo;BMAsia&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;).</p>
          </section>

          <section>
            <h2 className="font-headline text-2xl text-white mb-4">2. Our Services</h2>
            <p>BMAsia provides licensed background music solutions for commercial venues including hotels, restaurants, retail stores, and other businesses. The Site provides information about our services, allows you to request quotations, and offers a chat feature for inquiries.</p>
          </section>

          <section>
            <h2 className="font-headline text-2xl text-white mb-4">3. Quotations & Pricing</h2>
            <p>Pricing information shown on the Site is indicative only and may vary based on your specific requirements, location, number of zones, and contract terms. Final pricing is confirmed in a formal quotation or contract.</p>
            <p className="mt-3">Quotations provided through the Site or via email are valid for 30 days unless otherwise stated.</p>
          </section>

          <section>
            <h2 className="font-headline text-2xl text-white mb-4">4. AI Chat Assistant</h2>
            <p>The Site includes an AI-powered chat assistant. Please note:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Responses are generated by artificial intelligence, not a human</li>
              <li>Information provided is for general guidance only</li>
              <li>AI responses do not constitute binding offers, contracts, or professional advice</li>
              <li>For formal commitments, please contact our team directly</li>
            </ul>
          </section>

          <section>
            <h2 className="font-headline text-2xl text-white mb-4">5. Intellectual Property</h2>
            <p>All content on the Site — including text, images, design, logos, and software — is owned by BMAsia or its licensors and is protected by copyright and trademark laws. You may not reproduce, distribute, or create derivative works from our content without written permission.</p>
            <p className="mt-3">The BMAsia name, logo, &ldquo;Soundtrack Your Brand&rdquo;, and &ldquo;Beat Breeze&rdquo; are trademarks of BMAsia or its partners.</p>
          </section>

          <section>
            <h2 className="font-headline text-2xl text-white mb-4">6. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Use the Site for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with the operation of the Site</li>
              <li>Submit false or misleading information through our forms</li>
              <li>Use automated tools to scrape or copy content from the Site</li>
            </ul>
          </section>

          <section>
            <h2 className="font-headline text-2xl text-white mb-4">7. Third-Party Links</h2>
            <p>The Site may contain links to third-party websites (e.g., Calendly for booking demos, Soundtrack Your Brand). We are not responsible for the content, privacy practices, or availability of these external sites.</p>
          </section>

          <section>
            <h2 className="font-headline text-2xl text-white mb-4">8. Limitation of Liability</h2>
            <p>The Site and its content are provided &ldquo;as is&rdquo; without warranties of any kind. To the maximum extent permitted by law, BMAsia shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Site.</p>
            <p className="mt-3">This does not affect your statutory rights as a consumer where applicable.</p>
          </section>

          <section>
            <h2 className="font-headline text-2xl text-white mb-4">9. Governing Law</h2>
            <p>These terms are governed by the laws of the Kingdom of Thailand. Any disputes shall be subject to the exclusive jurisdiction of the courts of Thailand.</p>
            <p className="mt-3">For clients contracting with BMAsia Limited (Hong Kong), the laws of the Hong Kong Special Administrative Region shall apply to the relevant service agreement.</p>
          </section>

          <section>
            <h2 className="font-headline text-2xl text-white mb-4">10. Changes</h2>
            <p>We may update these terms from time to time. The current version will always be available on this page with the &ldquo;Last updated&rdquo; date. Continued use of the Site constitutes acceptance of any changes.</p>
          </section>

          <section>
            <h2 className="font-headline text-2xl text-white mb-4">11. Contact</h2>
            <p>
              Email: <a href="mailto:info@bmasiamusic.com" className="text-brand-orange hover:underline">info@bmasiamusic.com</a><br />
              BMAsia (Thailand) Co., Ltd.<br />
              725 S-Metro Building, Suite 144, Level 20<br />
              Sukhumvit Road, Klongtan Nua, Watthana<br />
              Bangkok 10110, Thailand
            </p>
          </section>
        </div>
      </article>
    </main>
  );
}
